FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
# Install Zabbix server
RUN apt update &&\
    apt install curl -y &&\
    apt install &&\
	wget https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb &&\
    dpkg -i zabbix-release_4.0-2+bionic_all.deb &&\
    apt update
    