# Docker-compose file for running Zabbix (and its env)
 version: '3'
 services:
# Create container with MySQL
   zabbix-mysql:
     restart: always
     image: mysql:5.6
     container_name: zabbix-mysql
     ports:
       - '3306:3306'
     environment:
       MYSQL_ROOT_PASSWORD: zabbix
     volumes:
       - /root/zabbix/mysql-data:/var/lib/mysql
# Create container with Zabbix server zabbix-server-mysql:ubuntu-4.4-latest
   zabbix-server:
     restart: always
     image: zabbix/zabbix-server-mysql:ubuntu-4.4-latest
     container_name: zabbix-server
     environment:
       DB_SERVER_HOST: "zabbix-mysql"
       MYSQL_USER: root
       MYSQL_PASSWORD: zabbix
     ports:
       - '10051:10051'
     links:
       - zabbix-mysql
     depends_on:
       - zabbix-mysql
# Create container with Zabbix front-end	 from image zabbix-web-nginx-mysql:ubuntu-4.4-latest
   zabbix-web:
     restart: always    
     image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.4-latest
     container_name: zabbix-web
     environment:
       DB_SERVER_HOST: zabbix-mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: zabbix
       ZBX_SERVER_HOST: "zabbix-server"
       PHP_TZ: Europe/Kiev
     ports:
       - '80:80'
       - '443:443'
     links:
       - zabbix-mysql
       - zabbix-server
     depends_on:
       - zabbix-mysql
       - zabbix-server
